blank_issues_enabled: false
contact_links:
  - name: Issue reporting disabled
    url: https://github.com/Sanji78/lepro_led/discussions
    about: Only collaborators can report issues â€” please use Discussions instead.
